### PR TITLE
Use union of strings for Cache in core

### PR DESCRIPTION
**Pull request by snnsnn**
Using union of strings for `Cache` type inside the core package improves clarity and code readability. Clearly you did not want to use an enum to avoid property lookup. This solution even removes the variable lookup. There is performance gain but not that significant. 

```typescript
type Cache =
  | 'CLEAN'
  | 'CHECK'
  | 'DIRTY';

type CacheWithoutClean = Exclude<Cache, 'CLEAN'>;
```

Please note that we still get type checking even though we use string expressions. For example, you will get type error for the following function:

```typescript
const checkIfDirty = (state: CacheState) => {
  return state !== 'CLEAX';
}
```

Code is also more readable due to more dicernible colors.

```typescript
if (this._value !== value && this.observers) {
  for (let i = 0; i < this.observers.length; i++) {
    this.observers[i].stale('DIRTY');
  }
}
```

It also eliminates possible future bugs emanating from zero being a falsy value, if implementation evolves into one that use the boolean logic over state values. 

I did some benchmarks using different bench-marking tools and platforms, i.e benchmarjs, perf.link, jsben.ch and sbench.me, proposed implementation has generally better performance over current one but from time to time current implementation won.

I was hoping for far more performance gain since we amortize the variable lookup but I guess browser engine does that for both implementations.

### CODE REVIEW

**Comment by modderme123** [comment]
This sounds interesting... Happen to have a link to one of the benchmarks?

**Comment by snnsnn** [comment]
> This sounds interesting... Happen to have a link to one of the benchmarks?

https://jsben.ch/wnnIi

**Comment by modderme123** [comment]
I like the idea of using strings unions to make things clearer and potentially faster, and that is a common technique in JavaScript to make APIs explicit. 

In TypeScript however, we have the luxury of using types which get compiled away. If you're interested, one alternative to prevent using 0 in the code (a compiler should still optimize this away) would be to add type brands to typescript.

In a lower level language I would expect that the cost of strings is higher than reading a variable, and that is what I see here: those benchmarks show the current implementation being slightly faster and slightly smaller than new implementation for me.

**Comment by snnsnn** [comment]
> one alternative to prevent using 0 in the code (a compiler should still optimize this away) would be to add type brands to typescript.

I don't know that method. Do you mean named enums like:

```typescript
enum Cache {
  Clean = 'Clean',
  Dirty = 'Dirty',
  Check = 'Check',
}
```
If so, I thought you intentionally avoid them because they produce very verbose output and performance degrades considerably:

```javascript
var Cache;
(function (Cache) {
    Cache["Clean"] = "Clean";
    Cache["Dirty"] = "Dirty";
    Cache["Check"] = "Check";
})(Cache || (Cache = {}));
```

Actually my initial intention was providing an enum like the one above, but realized its performance cost after running some test and switched to proposed implementation.

**Comment by snnsnn** [comment]
I have a question about stale checking:

```typescript
  private stale(state: CacheNonClean): void {
    
    // Does this means `this.state === 'CLEAN'`
    // since 0 | 1 | 2 < 1 | 2 and CacheWithoutClean is never 0
    if (this.state < state) { }
  }
```
This makes inner conditional `if (this.state === CacheClean && this.effect) EffectQueue.push(this);` redundant hence practically equivalent to:

```typescript
  private stale(state: CacheWithoutClean): void {
    if (this.state === 'CLEAN') {
      // If we were previously clean, then we know that we may need to update to get the new value
      if (this.effect) EffectQueue.push(this);

      this.state = state;

      if (this.observers) {
        for (let i = 0; i < this.observers.length; i++) {
          this.observers[i].stale('CHECK');
        }
      }
    }
  }
```

**Comment by modderme123** [comment]
That isn't quite correct. The first marking of stale takes nodes from CHECK to DIRTY (this.state == 1 && state == 2)
(I would expect that running the test suite should catch this, if it doesn't I'd love to know)

**Pull request closed without merging**
